package src;

import java.awt.Point;
import java.awt.event.ActionEvent;
import javax.swing.table.TableColumn;
import static src.Constantes.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author keke
 */
@SuppressWarnings("serial")
public class Fenetre extends javax.swing.JFrame {
	private Terrain carte;
    
    /**
     * Creates new form Fenetre
     */
    public Fenetre(Terrain arene) throws InterruptedException {
    	carte = arene;
        initComponents();
        jTable1.setRowHeight((jPanel1.getHeight()-jTable1.getTableHeader().getHeight())/ARENE_HEIGHT-5);
        TableColumn col;
        for(int i=0 ; i<ARENE_WIDTH+1 ; i++){
            col = jTable1.getColumnModel().getColumn(i);
            col.setPreferredWidth(jPanel1.getWidth()/(ARENE_WIDTH+1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addHaut = new javax.swing.JButton();
        addBas = new javax.swing.JButton();
        addGauche = new javax.swing.JButton();
        addDroite = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        delHaut = new javax.swing.JButton();
        delBas = new javax.swing.JButton();
        delGauche = new javax.swing.JButton();
        delDroite = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addObstacle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vue Terrain");

        jTable1.setModel(new TableModel(carte));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        addHaut.setText("HAUT");
        addHaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHautActionPerformed(evt);
            }
        });

        addBas.setText("BAS");
        addBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBasActionPerformed(evt);
            }
        });

        addGauche.setText("GAUCHE");
        addGauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGaucheActionPerformed(evt);
            }
        });

        addDroite.setText("DROITE");
        addDroite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDroiteActionPerformed(evt);
            }
        });

        jLabel1.setText("Ajouter un Mur");

        delHaut.setText("HAUT");
        delHaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delHautActionPerformed(evt);
            }
        });

        delBas.setText("BAS");
        delBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBasActionPerformed(evt);
            }
        });

        delGauche.setText("GAUCHE");
        delGauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delGaucheActionPerformed(evt);
            }
        });

        delDroite.setText("DROITE");
        delDroite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDroiteActionPerformed(evt);
            }
        });

        jLabel2.setText("Supprimer un Mur");

        addObstacle.setText("AJOUTER OBSTACLE");
        addObstacle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObstacleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addGauche, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(delDroite, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(addDroite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addBas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addHaut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(delGauche, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addComponent(delHaut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(delBas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(addObstacle)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addHaut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addGauche, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDroite, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delHaut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delBas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delGauche, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delDroite, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addObstacle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDroiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDroiteActionPerformed
        // TODO add your handling code here:
        int x = jTable1.getSelectedRow();
        int y = jTable1.getSelectedColumn()-1;
        carte.addMur(new Point(x, y), DROITE);
        Case caseTmp = carte.getCase(new Point(x, y));
        jTable1.setValueAt(caseTmp, caseTmp.getX(), caseTmp.getY());
        jTable1.changeSelection(x, y+1, false, false);
        jTable1.requestFocus();
    }//GEN-LAST:event_addDroiteActionPerformed

    private void delDroiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDroiteActionPerformed
        // TODO add your handling code here:
        int x = jTable1.getSelectedRow();
        int y = jTable1.getSelectedColumn()-1;
        carte.addNoMurs(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1), DROITE);
        Case caseTmp = carte.getCase(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1));
        jTable1.setValueAt(caseTmp, caseTmp.getX(), caseTmp.getY());
        jTable1.changeSelection(x, y+1, false, false);
        jTable1.requestFocus();
    }//GEN-LAST:event_delDroiteActionPerformed

    private void delHautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delHautActionPerformed
        // TODO add your handling code here:
        int x = jTable1.getSelectedRow();
        int y = jTable1.getSelectedColumn()-1;
        carte.addNoMurs(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1), HAUT);
        Case caseTmp = carte.getCase(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1));
        jTable1.setValueAt(caseTmp, caseTmp.getX(), caseTmp.getY());
        jTable1.changeSelection(x, y+1, false, false);
        jTable1.requestFocus();
    }//GEN-LAST:event_delHautActionPerformed

    private void addHautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHautActionPerformed
        // TODO add your handling code here:
        int x = jTable1.getSelectedRow();
        int y = jTable1.getSelectedColumn()-1;
        carte.addMur(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1), HAUT);
        Case caseTmp = carte.getCase(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1));
        jTable1.setValueAt(caseTmp, caseTmp.getX(), caseTmp.getY());
        jTable1.changeSelection(x, y+1, false, false);
        jTable1.requestFocus();
    }//GEN-LAST:event_addHautActionPerformed

    private void addBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBasActionPerformed
        // TODO add your handling code here:
        int x = jTable1.getSelectedRow();
        int y = jTable1.getSelectedColumn()-1;
        carte.addMur(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1), BAS);
        Case caseTmp = carte.getCase(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1));
        jTable1.setValueAt(caseTmp, caseTmp.getX(), caseTmp.getY());
        jTable1.changeSelection(x, y+1, false, false);
        jTable1.requestFocus();
    }//GEN-LAST:event_addBasActionPerformed

    private void addGaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGaucheActionPerformed
        // TODO add your handling code here:
        int x = jTable1.getSelectedRow();
        int y = jTable1.getSelectedColumn()-1;
        carte.addMur(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1), GAUCHE);
        Case caseTmp = carte.getCase(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1));
        jTable1.setValueAt(caseTmp, caseTmp.getX(), caseTmp.getY());
        jTable1.changeSelection(x, y+1, false, false);
        jTable1.requestFocus();
    }//GEN-LAST:event_addGaucheActionPerformed

    private void delBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBasActionPerformed
        // TODO add your handling code here:
        int x = jTable1.getSelectedRow();
        int y = jTable1.getSelectedColumn()-1;
        carte.addNoMurs(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1), BAS);
        Case caseTmp = carte.getCase(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1));
        jTable1.setValueAt(caseTmp, caseTmp.getX(), caseTmp.getY());
        jTable1.changeSelection(x, y+1, false, false);
        jTable1.requestFocus();
    }//GEN-LAST:event_delBasActionPerformed

    private void delGaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delGaucheActionPerformed
        // TODO add your handling code here:
        int x = jTable1.getSelectedRow();
        int y = jTable1.getSelectedColumn()-1;
        carte.addNoMurs(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1), GAUCHE);
        Case caseTmp = carte.getCase(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1));
        jTable1.setValueAt(caseTmp, caseTmp.getX(), caseTmp.getY());
        jTable1.changeSelection(x, y+1, false, false);
        jTable1.requestFocus();
    }//GEN-LAST:event_delGaucheActionPerformed

    private void addObstacleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObstacleActionPerformed
        // TODO add your handling code here:
        int x = jTable1.getSelectedRow();
        int y = jTable1.getSelectedColumn()-1;
        carte.addObstacle(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1);
        Case caseTmp = carte.getCase(new Point(jTable1.getSelectedRow(), jTable1.getSelectedColumn()-1));
        jTable1.setValueAt(caseTmp, caseTmp.getX(), caseTmp.getY());
        jTable1.changeSelection(x, y+1, false, false);
        jTable1.requestFocus();
    }//GEN-LAST:event_addObstacleActionPerformed

	/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBas;
    private javax.swing.JButton addDroite;
    private javax.swing.JButton addGauche;
    private javax.swing.JButton addHaut;
    private javax.swing.JButton addObstacle;
    private javax.swing.JButton delBas;
    private javax.swing.JButton delDroite;
    private javax.swing.JButton delGauche;
    private javax.swing.JButton delHaut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
